### ISSUE TITLE
Update Languagetool version

### ISSUE THREAD

**Issue by lbischof** [rhysd/vim-grammarous#21]
Languagetool is now version 3.1

**Comment by rhysd** [comment]
OK, I'll fix it later.

But you can try to specify the URL of language-tool as below.

```vim
let g:grammarous#jar_url = 'http://path/to/your/favorite/language-tools.zip'
```

**Comment by sgur** [comment]
LanguageTool version 3.2 was [released](http://forum.languagetool.org/t/announcement-languagetool-3-2/681), too.

But this version requires Java 8.
I have no idea that which version is more suitable as default.

https://www.languagetool.org/download/LanguageTool-3.2.zip

**Comment by rhysd** [comment]
Yes, I thought the same.

I must investigate which version is suitable for default value.  At least OS X now uses Java8 by default.

**Comment by tyru** [comment]
@rhysd Maybe you can also determine which version is suitable by `:if`.
Abstract code is here:

```viml
let s:java_ver = matchstr(systemlist('java -version')[0], 'version "\zs.*\ze"')
if s:is_greater_than(s:java_ver, 1.8)
    let g:grammarous#jar_url = <LanguageTool 3.2>
elseif s:is_greater_than(s:java_ver, 1.7)
    let g:grammarous#jar_url = <LanguageTool 3.1>
else
    ...
endif
```

**Comment by rhysd** [comment]
@tyru 

I don't think Java version is problem (sorry for confusing).  I think I can limit Java version >= 8 for vim-grammarous.

What I must investigate is that major version update (3.0) doesn't break vim-grammarous.  If vim-grammarous can work with LanguageTool 3.0+,  I will update the URL and update Java version requirement to 8.

**Comment by fncll** [comment]
Have you any update on possibly using Grammarous with the more recent versions of LanguageTool?

**Comment by rhysd** [comment]
Although default version is old, you can specify `g:grammarous#jar_url` to use latest version of LanguageTool.  Did you try that?

**Comment by sappo** [comment]
Just specified latest languagetool jar url and everything works just fine!

**Comment by rhysd** [comment]
@sappo 

Thank you for the report.  You mean v3.4?

**Comment by sappo** [comment]
Yes

**Comment by rhysd** [comment]
I'll upgrade the default version to v3.4 and will close this issue :+1:
