### ISSUE TITLE
No help, no vim plugin

### ISSUE THREAD

**Issue by thinca** [rhysd/vim-grammarous#22]
We need help.

**Comment by tyru** [comment]
It seems a マサカリ is thrown by マンボウ.

**Comment by thinca** [comment]
:muscle:

**Comment by rhysd** [comment]
> No help, no vim plugin

I don't think so.  README already exists.  I want to avoid extra work and manage duplicate document.

**Comment by thinca** [comment]
:-1:

**Comment by rhysd** [comment]
@thinca 

もし本当にこの issue が fix されるべきだと考えていらっしゃるのでしたら，その理由をちゃんと分かる形で記述して新しい issue を立ててください．PR であればパッチがその意図を伝えるのを手伝ってくれますが，これは issue ですので，ちゃんと伝わるように記述してください．あと No help, no vim plugin の根拠も分かりません．

**Comment by rhysd** [comment]
@thinca 

僕が issue を閉じコメントを lock した理由は以下です

- タイトルが意味不明
- issue 本体にも理由が無い
