### ISSUE TITLE
help がない

### ISSUE THREAD

**Issue by thinca** [rhysd/vim-grammarous#23]
久しぶりに grammarous を使おうとして、使い方をすっかり忘れてしまったのでヘルプを参照しようと `:help grammarous` を実行しましたが、使い方が書かれていませんでした。
いちいちブラウザを開かないと使い方が参照できないのはとてつもなく不便だと感じたので、help があると嬉しいです。

**Comment by rhysd** [comment]
なるほど，では Basic Usage について doc に追加します．

**Comment by rhysd** [comment]
ユースケースに対して充分な内容の help だと思うので，この issue は閉じます．

蛇足ですが，本件

- 特に理由も書かず雑な issue 立てで
- それに対してこちらはちゃんと考えて理由を伝えてやらないと close し，
- README へのリンクを help ファイルに記載するワークアラウンドも追加したのに対し，
- （技術的なハードルが特に無く，README もある本件に対して）「じゃあ PR 出すわ」どころか「:-1:」単体のコメントをされた

という4点でカチンときたことをお伝えしておきます．

**Comment by thinca** [comment]
まずは対応ありがとうございました。
今回は、@rhysd さんであれば Vim プラグインにおける help の重要性について理解しているに違いない、と言う私の勝手かつ一方的な思い込みがあり、その辺りの認識のすり合わせを怠り、結果として独善的な態度になってしまい、非常に不快な思いをさせてしまったことについて、大変申し訳ありませんでした。
深く反省し、今後はこのようなことがないよう、経緯の説明などを怠らないよう努めたいと思います。
未熟な身ではございますが、今後とも変わらぬお付き合いを頂けますよう心よりお願い申し上げます。

**Comment by tyru** [comment]
@rhysd 
自分も煽るようなコメントを書き込んでしまって大変申し訳ありませんでした。
文脈を欠いた発言をした事について深くお詫び申し上げます。

**Comment by rhysd** [comment]
いえ，分かっていただければ大丈夫です．（変な誤解があったら困ると思ったので，言い過ぎ感はありましたが全部書きました）また，勉強会等で会った時はよろしくお願いします．

余談ですが，僕はあまり help を重視していないです．（例えば，commitia.vim，vim-crystal などなど）
