### ISSUE TITLE
Problem: vim-grammarous cannot do background checks

### ISSUE THREAD

**Issue by sappo** [rhysd/vim-grammarous#27]
Hi,

this is something I like to help with. The lastest version of language-tool offers a REST-JSON API that can be queried simultaniously. Here are some issue I need help with to resolve:
- How do I send HTTP request with vimscript?
- How do I parse JSON with vimscript?
- How do I split a vim buffer in paragraphs or something similar (parallel buffer check)?
- How can I get the current paragraph that a user is editing to do background checks?

Regards
Kevin

**Comment by rhysd** [comment]
Now vim-grammarous uses Vim8's job feature. It enables asynchronous check in background. Please try the latest.

**Comment by sappo** [comment]
@rhysd that's great! Are there any incompatibilities with your plugins that you discovered using vim8. I.e. neovim, etc.

**Comment by rhysd** [comment]
Currently I'm not seeing any regression yet. vim-grammarous only supports Vim8 currently. So in Neovim it still blocks while running a checker.

**Comment by sappo** [comment]
Sorry, neovim is wrong. I meant neobundle, clever-f, etc

**Comment by rhysd** [comment]
I'm using neobundle, clever-f,... and it looks working well together 👍
