### ISSUE TITLE
Use system languagetool

### ISSUE THREAD

**Issue by Yamakaky** [rhysd/vim-grammarous#28]
Is it possible? For example, it's in archlinux's repos.

**Comment by rhysd** [comment]
I don't know how languagetool is installed to system.  Is some command installed? And how can I try it?  Please give me more information.

**Comment by tyru** [comment]
@Yamakaky maybe you should paste the output of `pacman -Ql <pkg>` to gist or anywhere?
I also don't have arch linux environment now though.

**Comment by Yamakaky** [comment]
https://0bin.net/paste/doHK6NsWqq+93OYF#b8Sm6Qw-k2mKSfKiyTiB/1NP92zm91CAbbYj+pOC8eU

**Comment by rhysd** [comment]
@Yamakaky Please update plugin and use `g:grammarous#languagetool_cmd`

**Comment by Yamakaky** [comment]
cool!
