### ISSUE TITLE
Navigation within buffer itself (quickfix used as just an info window)

### ISSUE THREAD

**Issue by HarishVangala** [rhysd/vim-grammarous#34]
First of all, this is a simple yet powerful tool. A must add-on for writers, for its amazing use.

I am annoyed at only one issue: I am not able to comfortably navigate among errors, it involves multiple steps such as moving to quickfix window and then pressing `n` or `p`  and then again move to quickfix window and so on.

This feels uncomfortable because in the default `:set spell` utility itself, I can jump easily using `[s` and `]s`. In the current example say, we may use simply `n` and `p`  (until `:GrammarousReset` used) to move from current error to next, understand from the quickfix window what went wrong at that place correct and move on.  In otherwords, it is simply the way the infamous spell-check works in MS-Word.

Is this feature-addition possible?? Please let me know.

**Comment by rhysd** [comment]
Did you try custom mappings?

https://github.com/rhysd/vim-grammarous#plug-mappings-to-execute-actions-anywhere

I guess what you want is:

```vim
nmap <C-g><C-n> <Plug>(grammarous-move-to-next-error)
nmap <C-g><C-p> <Plug>(grammarous-move-to-previous-error)
```

In above example, you can jump between errors with `<C-g><C-n>` and `<C-g><C-p>`. If you want to avoid defining global keymaps, please refer below document.

https://github.com/rhysd/vim-grammarous#i-want-to-use-above-plug-mappings-only-after-checking

**Comment by HarishVangala** [comment]
I think that's a good solution.

Thanks a lot!
Harish V.
