### ISSUE TITLE
Unknown function: vital#grammarous#new

### ISSUE THREAD

**Issue by fszymanski** [rhysd/vim-grammarous#36]
I get this error after the vital modules update:
```
Error detected while processing /home/xyz/.local/share/nvim/dein/repos/github.com/rhysd/vim-grammarous/autoload/grammarous.vim:
line 4:
E117: Unknown function: vital#grammarous#new
E15: Invalid expression: vital#grammarous#new()
```

**Comment by rck** [comment]
Same for me (+ lots of other errors following). For now I switched back to 74a88d233056a (currently HEAD^) which fixed the issue. I use the standard vim shipped in current Debian/testing

**Comment by rhysd** [comment]
ah, sorry I had mistaken...

**Comment by rhysd** [comment]
It should be fixed now. I'm sorry for inconvenience...
