### ISSUE TITLE
Fails with `fish` being used a default shell.

### ISSUE THREAD

**Issue by dpc** [rhysd/vim-grammarous#38]

**Comment by rhysd** [comment]
I'm not using fish so I don't know how to fix. PR is welcome

**Comment by languitar** [comment]
There are a lot of things that break if fish is used as the shell inside vim because it is not sh-compliant. I would recommend to configure vim to use bash as its internal shell using

```
set shell=bash
```

You are still free to use fish for neovim's terminal emulator etc.

**Comment by rhysd** [comment]
@languitar's advice is reasonable. I also recommend to set 'shell' option.

I'm closing this because there is no response from issue author.
