### ISSUE TITLE
vim-grammarous: Grammar check was failed with exit status 1

### ISSUE THREAD

**Issue by wagglefoot** [rhysd/vim-grammarous#41]
Hi there, I am getting the following error message when after I follow all the instructions in installing grammarous:

`vim-grammarous: Grammar check was failed with exit status 1`

It has installed `LanguageTool` in the right place, and I installed the package using `Vundle`. The excerpt from my `.vimrc` is as so:

`Plugin 'rhysd/vim-grammarous'` -- perhaps that is not correct? 

Any insights would be greatly appreciated, seems like an excellent plugin.

**Comment by rhysd** [comment]
Could you show the entire error message? Taking a screenshot of the error would also be great.

**Comment by wagglefoot** [comment]
![screenshot from 2017-06-17 17-39-34](https://user-images.githubusercontent.com/5817673/27254647-780966ac-5384-11e7-95c6-e46048a47903.png)

**Comment by rhysd** [comment]
Could you try following? We need to clarify the command failure is an error of vim-grammarous or LanguageTools itself because of no stderr output.

```diff
diff --git a/autoload/grammarous.vim b/autoload/grammarous.vim
index 11d247d..0cea510 100644
--- a/autoload/grammarous.vim
+++ b/autoload/grammarous.vim
@@ -254,6 +254,8 @@ function! s:invoke_check(range_start, ...)
         let cmd = printf('%s -jar %s %s', g:grammarous#java_cmd, substitute(jar, '\\\s\@!', '\\\\', 'g'), cmdargs)
     endif
 
+    echomsg 'Command: ' . cmd
+
     if s:job_is_available
         let job = job_start(cmd, {'close_cb' : s:SID . 'on_check_done_vim8', 'exit_cb' : s:SID . 'on_check_exit_vim8'})
         echo 'Grammar check has started with job(' . job . ')...'
```

1. `cd` to the vim-grammarous repo
2. Copy above diff and write it to `patch.diff` file
3. `git apply patch.diff`
4. Reproduce the error
5. It should output `Cmd: ...` to `:message` area. What did it say?
6. And try the command from your shell directly. Did it also fail?

**Comment by wagglefoot** [comment]
Sorry, I am probably being a bit stupid here, so you're going to have to be super explicit. 

Having cloned `vim-grammarous` and then `cd` there, there are no `a` or `b` dirs (this is where you do a face-palm no doubt - sorry). Nor does `diff` have a `--git` option (do you mean `git diff`).

**Comment by rhysd** [comment]
You're using Vundle. So I think vim-grammarous was already cloned into somewhere in your filesystem (`~/.vim/bundle/vim-grammarous`?) by Vundle. You don't need to newly clone repo.

Please copy diff in above comment (or [here](https://gist.githubusercontent.com/rhysd/f496a5b1fad2c04f41711bced3202884/raw/819d69ae2d97f6cb36a6d6f67ef965daa033771d/diff.patch). Then copy the diff as file `patch.diff` and apply it with `git apply patch.diff`.

**Comment by wagglefoot** [comment]
Yupp the plugin lives here:

`~/.vim/bundle/vim-grammarous`

The returned error after applying the patch is:

```
error: patch failed: autoload/grammarous.vim:254
error: autoload/grammarous.vim: patch does not apply
```

**Comment by rhysd** [comment]
Your repo may not be the latest. At least in my repo, `git apply` did not raise the error. If your repo is currently not the latest, please ensure that this problem occurs also with the latest.

Anyway, I think adding one line directly is easier. Please open `autoload/grammarous.vim` and find line ` if s:job_is_available`. Just before the line, please add `echomsg 'Command: ' . cmd` like above diff. And please reproduce this issue and see the message area.

**Comment by JackeJR** [comment]
Just to chime in. I had the same error. For me, it boils down to LanguageTools using another version of Java (which was quite old) present in my path. Rearranging the precedence of paths in my PATH to make sure the latest version is ahead fixed the issue.

**Comment by rhysd** [comment]
@JackeJR Thank you for the info. Which version Java did solve the problem?

**Comment by JackeJR** [comment]
The one I used was Java 8 131. Only Java 8 is supported.

https://github.com/languagetool-org/languagetool/blob/master/languagetool-standalone/README.md

**Comment by rhysd** [comment]
Oh, I see. As described in README, Java8+ is required. Thank you for your information.

**Comment by mmaret** [comment]
Also got this error with Ubuntu 18.04 and java 10.

Adding the `echomsg` patch show the following error 
`Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException`

According to this stackoverflow thread https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j I quick fix it by modifying the cmd to

       `  let cmd = printf('%s -jar --add-modules java.xml.bind %s %s', g:grammarous#java_cmd, substitute(jar, '\\\s\@!', '\\\\', 'g'), cmdargs)`

**Comment by thanasisn** [comment]
> Also got this error with Ubuntu 18.04 and java 10.
> 
> Adding the `echomsg` patch show the following error `Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException`
> 
> According to this stackoverflow thread https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j I quick fix it by modifying the cmd to
> 
> ```
>    `  let cmd = printf('%s -jar --add-modules java.xml.bind %s %s', g:grammarous#java_cmd, substitute(jar, '\\\s\@!', '\\\\', 'g'), cmdargs)`
> ```

Hello,
Where did you do the above change?
I have the same problem.
I tested the jar files of languagetool and are running in my system, but fail in vim Grammarous

**Comment by mmaret** [comment]
@thanasisn ,
That's an old story but I think it is in the "autoload/grammarous.vim" file. Today it is around line 328 for me.
The file location can depends on the way you install this plugin.
It could be in $HOME/.vim/autoload/grammarous.vim or $HOME/.vim/bundle//vim-grammarous/autoload/grammarous.vim or ...

**Comment by agherzan** [comment]
It seems to fail with java 8 too:

```
java -jar[...]/.vim/bundle/vim-grammarous/misc/LanguageTool-6.0/languagetool-commandline.jar -d WHITESPACE_RULE,EN_QUOTES -c utf-8 -l en --api /tmp/v0gFbsg/0
Unknown parameter: --api
```

openjdk version "1.8.0_352"
OpenJDK Runtime Environment (build 1.8.0_352-8u352-ga-1~22.04-b08)
OpenJDK 64-Bit Server VM (build 25.352-b08, mixed mode)

See: http://wiki.languagetool.org/command-line-options
```
Display LanguageTool output in XML API format - deprecated, please use the JSON API in server mode instead, which is usually faster, as it has no start up overhead.
```

EDIT: ^ this is https://github.com/rhysd/vim-grammarous/issues/110

**Comment by bondhugula** [comment]
I experience this same issue with no additional information on the error.

```
vim-grammarous: Grammar check failed with exit status 1:
```

```
$ java -version
openjdk version "11.0.21" 2023-10-17
OpenJDK Runtime Environment (build 11.0.21+9-post-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.21+9-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)
```

Ubuntu 22.04

vim-grammarous commit

```
commit db46357465ce587d5325e816235b5e92415f8c05 (HEAD -> master, origin/master, origin/HEAD)
Merge: a3d6740 8a4d1c4
Author: Linda_pp <rhysd@users.noreply.github.com>
Date:   Mon Nov 30 20:07:57 2020 +0900

    Merge pull request #87 from matze-dd/master
    
```
Printing out the command:

Command: java -jar /home/uday/.vim/bundle/vim-grammarous/misc/LanguageTool-6.3/languagetool-commandline.jar -d WHITESPACE_RULE,EN_QUOTES -c utf-8
-l en --api /tmp/vjnMAF0/1
