### ISSUE TITLE
Support for vim-plug

### ISSUE THREAD

**Issue by XVilka** [rhysd/vim-grammarous#42]
Mostly instructions though.

**Comment by rhysd** [comment]
What does 'support for vim-plug' actually mean?

1. There is a problem using vim-grammarous with vim-plug
2. Want an instruction to use vim-grammarous with vim-plug

If 1., please describe the detail.

If 2., to my understanding, vim-grammarous can be installed with vim-plug like other normal plugins. I feel vim-plug official instruction is enough to install vim-grammarous and no need to add special instruction in vim-grammarous README.

**Comment by rhysd** [comment]
Closing this as no response

**Comment by TimDaub** [comment]
For posterity:

```bash
cd $HOME/.vim/bundle
git clone git@github.com:rhysd/vim-grammarous.git
```

@rhysd lemme know if you want me to send a pr with this snippet in README.md.
