### ISSUE TITLE
vim stalls on simple pattern

### ISSUE THREAD

**Issue by videda** [rhysd/vim-grammarous#43]
When executing `:GrammrousCheck` in vim on a file containing the following pattern

~~~
a 

b
~~~

that is a line with a space at the end and two subsequent new lines, then after
I receive the report by grammarous (e.g. `Detected 3 grammatical error`), vim
stalls using 100% CPU. I can only stop it with Ctrl-C.

**Comment by rhysd** [comment]
I addressed this issue in d117cd1. Thank you for catching this!
