### ISSUE TITLE
Syntastic integration

### ISSUE THREAD

**Issue by DancingQuanta** [rhysd/vim-grammarous#48]
Would it be possible to use [Syntastic](https://github.com/vim-syntastic/syntastic) to navigate errors?

**Comment by rhysd** [comment]
I'm not syntastic user so I don't know this plugin is suitable for it and how to integrate. It's welcome to review PR for it.

**Comment by somini** [comment]
I'm proposing a PR for neomake for this usecase.
https://github.com/neomake/neomake/pull/1766
NeoMake is a Syntastic clone for neovim.

It's not a complete replacement, since this plugin presents all the information languagetool produces, while neomake it more limited.

**Comment by DancingQuanta** [comment]
I have forgotten to update. I have found that syntastic already have a linter for LanguageTool, which is a python executable called [language-check](https://pypi.python.org/pypi/language-check). `language-check` is a wrapper around LanguageTool and so produces differently formatted output.
Neomake should use this `language-check` instead.

**Comment by rhysd** [comment]
Syntastic already supports languagetools. So I think we can close this issue.
