### ISSUE TITLE
Repeated white space

### ISSUE THREAD

**Issue by junhyeokahn** [rhysd/vim-grammarous#49]
Hi, First of all I would really appreciate your awesome plugin!

I have two concerns.
1. I used to make double space when I start a sentence and grammarous check this a typo as below figure. I disable white space rule in my vimrc but still have it
<img width="36" alt="screen shot 2017-09-19 at 7 26 20 am" src="https://user-images.githubusercontent.com/23005104/30592331-edc4b74a-9d0b-11e7-9db7-7f393dc3596d.png">

2. I saw someone talking about using in tex. Are you planning to implement this for tex as well? I am so looking forward if you will.

Thank you

**Comment by rhysd** [comment]
What is warned are depending on config of LanguageTools. So please look into rules and disable the rule with `g:grammarous#disabled_rules`.

https://github.com/rhysd/vim-grammarous#some-rules-annoy-me

**Comment by rhysd** [comment]
For TeX, I think https://github.com/rhysd/vim-grammarous/issues/40 is the same topic. Please see the issue discussion.
