### ISSUE TITLE
support for pylanguagetool?

### ISSUE THREAD

**Issue by DerWeh** [rhysd/vim-grammarous#50]
I wanted to ask if it is also possible to support `pylanguagetool`? I find it very bothersome to get `LanguageTool` running on Debian, as it is difficult to get Java8, and using a legacy version of the `LanguageTool` is a bit cumbersome even if it's doable.
`pylanguagetool` on the other hand is just one `pip`-command away, as python is on every Linux by default.

Furthermore `pylanguagetool` seems to be a lot faster.

**Comment by rhysd** [comment]
Why Debian has difficulty for getting Java8? Doesn't openjdk8 work?

Supporting another tool makes this app much more complicated. So I don't want to do that until I understand it has some great advantage.

**Comment by DerWeh** [comment]
I understand that additional support adds complication, the question was in the direction how hard it would be, as the output seems very similar.

Thanks for the `openjdk8` tip, somehow I didn't see that there is a back-port for `jessi`. I will try it as soon as I have time. Still, python would be more enjoyable for me as I don't need root rights, I can just do `pip install --user pylanguagetool`. At University, I would have to contact the system administrator.

I should further inquire the speed. On my machine  the Java version took 12s for a sample document every run, while python took only 7s and successive calls were basically instant. To get a reliable  timing I need a workaround for the caching. But if there really was a speed-up of 40% it would justify support (or even change to) the python version. At least to me speed is quite crucial for a language checker, but of course I don't know how hard the support would be to implement.

**Comment by rhysd** [comment]
Thank you for the info. If output/input is very similar to LanguageTool, I may consider to integrate it. Anyway I need to investigate.
