### ISSUE TITLE
Error message when quitting the check window with

### ISSUE THREAD

**Issue by languitar** [rhysd/vim-grammarous#53]
When I close the checking window with `q`, I always see the following error message:

```
Error detected while processing function grammarous#info_win#action_quit:
line    3:
E108: No such variable: "b:grammarous_preview_bufnr"
```

**Comment by rhysd** [comment]
Could you provide more information about your environment to reproduce problem? At least it does not reproduce in my local.

- Vim version (i.e. 7.4.x or 8.0.x or Neovim 2.x or ...)
- Your OS

**Comment by rhysd** [comment]
I improved to close preview window. Could you try out the latest?

**Comment by languitar** [comment]
This is gone with the update. :)  I am running neovim 0.2.2 on Linux.

**Comment by rhysd** [comment]
Yes. Thank you for confirming. I’m closing this.

**Comment by languitar** [comment]
Is there any way to actually return to the correct buffer afterwards?

**Comment by rhysd** [comment]
Currently there is no way to do that. 'quit' action only `:quit` the window with cleanup.

**Comment by languitar** [comment]
I think I once had a discussion on how to achieve this reliably in vimtex in this issue: https://github.com/lervag/vimtex/issues/637 Maybe you could adapt the solution there?

**Comment by rhysd** [comment]
Actually I can implement it easily. Not understanding it's practically useful or not (because I'm satisfied with current behavior).

**Comment by languitar** [comment]
For my workflow I always have several windows open and of the cursor jumps back to a different one after closing the checking window, I actually have to do something to get it back to the window I was actually working in. So I'd appreciate a solution for that ;-)

**Comment by rhysd** [comment]
ok, I'll change the behavior of quit action.

**Comment by rhysd** [comment]
Please update to the latest and try out.

**Comment by languitar** [comment]
Seems to work well. Thanks!
