### ISSUE TITLE
Use of location-list

### ISSUE THREAD

**Issue by FabianGeiselhart** [rhysd/vim-grammarous#60]
I think it would be a good idea to put the Error (not the suggested fix) into the location-list.

This would make moving between errors via `:lNext` and `:lPrevious`

**Comment by rhysd** [comment]
It would be a good idea. I think I need to try

**Comment by rhysd** [comment]
I implemented this. Please update to the latest and set `g:grammarous#use_location_list` to `1` in your vimrc

**Comment by FabianGeiselhart** [comment]
Nice!
