### ISSUE TITLE
Grammarous window disappears when fixing/ignoring error, etc.

### ISSUE THREAD

**Issue by thomaskisler** [rhysd/vim-grammarous#63]
When I do a :GrammarousCheck, the Grammarous window opens and shows me the first error. When I then e.g. press "f" to automatically fix it, it does, but the Grammarous window disappears. The only way to make it reappear is to find the next error and move the vim cursor "into it". The same holds true for all other Grammarous actions "r", "R", etc. 

Am I doing something wrong? I would expect the window to stay open. Or is it possible to make it reappear again, as a workaround?

As a side note: the Grammarous window loses its focus when I use "n", so that the next shortcut I will use will be issued in the normal vim window (though the Grammarous window is still visible). So it does not work for me, if I want to skip over two errors in a row, without refocusing the Grammarous window.

**Comment by rhysd** [comment]
I think you can map `<Plug>(grammarous-open-info-window)` to open the window or map `<Plug>(grammarous-move-to-next-error)` to move to the next error. Is this answer for you?

**Comment by rhysd** [comment]
Looks good. Could you create a pull request to update doc?
