### ISSUE TITLE
Passive voice not detected

### ISSUE THREAD

**Issue by pdoak** [rhysd/vim-grammarous#65]
Grammarous does not seem to detect the passive voice. I have taken the following sentence from The [Language Tool website](https://community.languagetool.org/rule/index) which is in the passive voice:

> Her work will have been finished by tonight.

Is it possible to highlight the use of the passive voice with Grammarous?

**Comment by rhysd** [comment]
Please update to the latest and try following config. I confirmed `PASSIVE_VOICE` rule is checked.

```vim
let g:grammarous#enabled_rules = {'*' : ['PASSIVE_VOICE']}
```

**Comment by pdoak** [comment]
That worked. Thank you.
