### ISSUE TITLE
Custom path for LanguageTool?

### ISSUE THREAD

**Issue by nick-s-b** [rhysd/vim-grammarous#67]
Hi,

I really like `vim-grammarous` a lot! The one thing I don't like is that it uses downloads its own local version of LanguageTool. That's a problem because it's not managed by the distro's update system. If there's any kind of security issue, it won't be updated. It' also wasteful since no other program will find it.

Has anyone found a way to `ln` a system-wide version of LT so `vim-grammarous` will recognize it? I've tried it but it didn't work: `ln -s /usr/share/java/languagetool/ <my_vim_path>/vim-grammarous/misc/LanguageTool-4.1`.

Thanks!

**Comment by rhysd** [comment]
[Yes.](https://github.com/rhysd/vim-grammarous#i-want-to-use-system-global-languagetool-command)
