### ISSUE TITLE
Execute the checker in background using vimproc

### ISSUE THREAD

**Issue by rhysd** [rhysd/vim-grammarous#7]
- Executing the checker for large file takes a while.
- Executing the checker in background and polling the result makes the process non-blocking.
- Non-blocking execution takes longer than blocking version.
  - It is good design that a user can chose blocking or non-blocking.
- I should start to resolve this issue after making dependency on vimproc optional.
- [Vital.Reunion](https://github.com/osyo-manga/vital-reunions) may be useful.
  - It makes executing in background easier.
  - It has a few tests.
  - It is not tested and developed in OS X. (Keep in mind that it may not work properly)

**Comment by somini** [comment]
One solution to this is to spawn the HTTP server in the background and send requests to it. The first request takes as long as a regular execution, but the following are 10x faster.

See:
https://github.com/neomake/neomake/issues/1728
https://github.com/neomake/neomake/pull/1766

**Comment by rhysd** [comment]
vim-grammarous is already using job features on both Vim8 and Neovim. So I think I should close this issue.

@somin It would also nice. I'll make another issue for it.
